### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by jimmygoogle** [microsoft/PartnerCenter-GDAPTransition#10]
I am trying to build the tool using the `dotnet run` command in Ubuntu and I get the following warnings and failures in the attached log.

[msft.log](https://github.com/microsoft/PartnerCenter-GDAPTransition/files/9294159/msft.log)
.

**Comment by manusidd** [comment]
Hello,
 I see this in the logs "enableMacOSCodeSign". I am trying to understand, was the .csproj file modified for macOS and used for Linux?

**Comment by jimmygoogle** [comment]
The issue appears to be caused by trying to build the tool inside a docker VM in a directory that is mounted to my local machine. The tool builds successfully both locally and inside the VM when not in the mounted directory. Closing this issue.
