### ISSUE TITLE
Associating multiple roles with a single group in securityGroup.csv not working

### ISSUE THREAD

**Issue by MisterCloudTech** [microsoft/PartnerCenter-GDAPTransition#18]
The documentation state that associating multiple roles with a single group in securityGroup.csv is done by:

"A list that must contain one or more (separated by commas) of the Azure AD role IDs that were defined in the ADRoles.csv file that were assigned to the newly created GDAP relationships."

In securityGroup.csv the security group object ID is listed first, then a comma, followed by the group name, another comma, and then the list of role IDs from the ADRoles.csv file, each seperated by a comma.

When doing this, and verifying the assignments in both the partner portal and in the customer tenant, only the **first** role is added assigned to the group, and the remaining roles appears to be ignored. 
I do not see any errors related to these multi-role assignments in either the console or displayed in accessAssignment.csv

How can multiple roles be correctly assigned to a single security group, and then displayed in the portal ?

**Comment by sansbacher** [comment]
Obvious, but worth asking: did you enclose the comma separated list of Role IDs with **double quotes**? (since, for reasons I can't begin to explain, the tool authors are using a comma separated list as a single item _within_ a Comma Separated Values file... sigh...)

Something like:

```
Id,DisplayName,CommaSeperatedRoles
806980ff-1234-5678-abcd-c2d3a55f1234,Full Access Group Name,"abc123abc-69f5-4237-9190-012177145678,cde876cde-3afb-46b9-b7cf-a126ee749876"
```

That worked for me.

**Comment by MisterCloudTech** [comment]
Thanks for the input @sansbacher, and a good point. 
No I have not enclosed the comma-separated list of Role ID with double quotes -  in the documentation example nor the describing text double quotes does not appear to be mentioned or illustrated anywhere.

But I will give it a try and report back.

Reference: https://docs.microsoft.com/en-us/partner-center/gdap-bulk-migration-tool#provision-security-groups

**Comment by MisterCloudTech** [comment]
I have tested this, and can confirm the observation raised by @sansbacher: 
The comma-separated list of Role IDs in the `securitygroup.csv` must be enclosed in **double quotes** to work correctly.

So an corrected documentation should be (article doesn't appear to be editable):

- **CommaSeperatedRoles** – A list that must contain one or more unique identifiers (separated by commas) of the Azure AD role(s) that were defined in the ADRoles.csv file and were assigned to the newly created GDAP relationships. When adding _multiple_ Azure AD role IDs, the list must be enclosed in **double quotes**. Example:

```
Id,DisplayName,CommaSeperatedRoles
806980ff-1234-5678-abcd-c2d3a55f1234,Full Access Group Name,"abc123abc-69f5-4237-9190-012177145678,cde876cde-3afb-46b9-b7cf-a126ee749876"
```
(Ref.: https://docs.microsoft.com/en-us/partner-center/gdap-bulk-migration-tool#provision-security-groups)

**Comment by sansbacher** [comment]
Glad to hear it!

Yes, I think this tool is sort of beta and needs some work (like, say, a Quit option :) .... hopefully it gets some updates now that people are using it.

**Comment by MisterCloudTech** [comment]
The "GDAP bulk migration tool" documentation article is now updated with the following addition in the "Provision security groups" section:

**Tip**
You might need to enclose each `CommaSeparatedRoles `value in qutotation marks (`""`).
