### ISSUE TITLE
Issue with assigning Security Groups

### ISSUE THREAD

**Issue by dwconnolly-cloud** [microsoft/PartnerCenter-GDAPTransition#20]
Hi,
I'm having an issue with the migration tool where it will not assign Security Groups with option 9. The tool seems to read the files and see the Security groups to be configured but doesn't create any of them. The accessAssignment file is blank, and there is nothing within the logs. I'm using csv files and have tried on multiple tenants and have tried to assign different groups and AD Roles all with the same result. The GDAP requests have been working correctly, and I can assign the security group via the Partner Center manually in the GUI. Any insight would be much appreciated. Thanks!

![image](https://user-images.githubusercontent.com/107204153/189700001-7467c12d-e70a-41bb-884b-71d96accf131.png)

**Comment by abc-RKN** [comment]
I have exactly the same issue. 

Also the gdapRelationShip does not show CustomerDelegatedAdminRelationshipId, nor statussus / Created date etc. (The gdap was created and when looking in the partner center I do see the GDAP relationship, and it IS active.

**Comment by dwconnolly-cloud** [comment]
I have found the issue to my problem. @abc-RKN I was not experiencing what you are referring to in your "In addition" section just FYI.

The issue was I was not updating the GdapRelationship file with option 8 after it was created and the program required the file to contain Active as the status instead of approved. I thought it was more informational for the user than required for the program to work correctly. Since the status of the relationship was in fact Active when I check it using option 5. But the updated GdapRelationship file was required to proceed.
