### ISSUE TITLE
[0: Error] PartnerLed.Providers.GdapProvider - Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by swanny246** [microsoft/PartnerCenter-GDAPTransition#36]
Attempting to run the program, whenever I go to perform operations including Downloading existing GDAP relationships, or downloading eligible customer lists, I get this error:

[0: Error] PartnerLed.Providers.GdapProvider - Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0.

This occurs no matter if I use CSV or JSON method. 

It was successful in creating the GDAP relationships, and they are showing as approved in the partner centre, however it doesn't update the CSV to reflect this, and therefore doesn't allow me to create the security groups-role assignments.

I am running Windows 11 and .Net SDK 6.0.

**Comment by Tylaeus** [comment]
@swanny246 I was having this issue in our own partner tenant - I've just tried this again today and it's allowed me to run through the next steps of adding our security groups.

I was getting the error on re-downloading existing relationships too - potentially something in the backend was fixed?

**Comment by manusidd** [comment]
Fixed with the following commit: https://github.com/microsoft/PartnerCenter-GDAPTransition/commit/4095943d4ec5ba0bcd568c1eabfacff39ece6833
